name: Publish
on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ">=3.9"

      # Install package with test extras and pytest
      - run: python -m pip install --upgrade pip build
      - run: pip install -e ".[test]" pytest build twine

      # Run tests; fail if anything breaks
      - run: pytest -q

      # Build and upload
      - run: python -m build
      - name: Upload to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: twine upload dist/*
